// Writes validated MunicipalityData as a TypeScript module into src/data/municipalities/
// so the app can import it statically (no JSON.parse at runtime).

import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { MunicipalityData } from './types.js'
import { assertValid } from './validate.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../src/data/municipalities')

// Prefecture code → English folder name mapping (ISO 3166-2:JP)
const PREFECTURE_FOLDER: Record<string, string> = {
  '東京都': 'tokyo', '大阪府': 'osaka', '愛知県': 'aichi',
  '神奈川県': 'kanagawa', '福岡県': 'fukuoka', '北海道': 'hokkaido',
  '宮城県': 'miyagi', '埼玉県': 'saitama', '千葉県': 'chiba',
  '兵庫県': 'hyogo', '広島県': 'hiroshima', '京都府': 'kyoto',
}

export function write(data: MunicipalityData): void {
  assertValid(data)

  const prefFolder = PREFECTURE_FOLDER[data.prefecture] ?? data.prefectureEn.toLowerCase().replace(/\s+/g, '_')
  const dir = join(ROOT, 'jp', prefFolder)
  mkdirSync(dir, { recursive: true })

  const outPath = join(dir, `${data.code}.ts`)
  const ts = generateTs(data)
  writeFileSync(outPath, ts, 'utf8')
  console.log(`✅ Written: ${outPath}`)
}

function generateTs(data: MunicipalityData): string {
  const json = JSON.stringify(data, null, 2)
    .replace(/"([a-zA-Z_]+)":/g, '$1:')  // unquote keys for cleaner TS
  return `// ${data.name} (${data.code}) — auto-generated by pipeline
// dataVersion: ${data.dataVersion}
import { Municipality } from '@/types/schedule'

const data: Municipality = ${json}

export default data
`
}
